// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createCommentCommentPost, createLecturerLecturerPost, deleteCommentCommentUuidDelete, deleteLecturerLecturerIdDelete, getCommentCommentUuidGet, getCommentsCommentGet, getLecturerByTimetableIdLecturerTimetableIdTimetableIdGet, getLecturerLecturerIdGet, getLecturersLecturerGet, importCommentsCommentImportPost, likeCommentCommentUuidReactionPut, type Options, reviewCommentCommentUuidReviewPatch, updateCommentCommentUuidPatch, updateLecturerLecturerIdPatch, updateLecturerRatingLecturerImportRatingPatch } from '../sdk.gen';
import type { CreateCommentCommentPostData, CreateCommentCommentPostError, CreateCommentCommentPostResponse, CreateLecturerLecturerPostData, CreateLecturerLecturerPostError, CreateLecturerLecturerPostResponse, DeleteCommentCommentUuidDeleteData, DeleteCommentCommentUuidDeleteError, DeleteCommentCommentUuidDeleteResponse, DeleteLecturerLecturerIdDeleteData, DeleteLecturerLecturerIdDeleteError, DeleteLecturerLecturerIdDeleteResponse, GetCommentCommentUuidGetData, GetCommentCommentUuidGetError, GetCommentCommentUuidGetResponse, GetCommentsCommentGetData, GetCommentsCommentGetError, GetCommentsCommentGetResponse, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetData, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetError, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetResponse, GetLecturerLecturerIdGetData, GetLecturerLecturerIdGetError, GetLecturerLecturerIdGetResponse, GetLecturersLecturerGetData, GetLecturersLecturerGetError, GetLecturersLecturerGetResponse, ImportCommentsCommentImportPostData, ImportCommentsCommentImportPostError, ImportCommentsCommentImportPostResponse, LikeCommentCommentUuidReactionPutData, LikeCommentCommentUuidReactionPutError, LikeCommentCommentUuidReactionPutResponse, ReviewCommentCommentUuidReviewPatchData, ReviewCommentCommentUuidReviewPatchError, ReviewCommentCommentUuidReviewPatchResponse, UpdateCommentCommentUuidPatchData, UpdateCommentCommentUuidPatchError, UpdateCommentCommentUuidPatchResponse, UpdateLecturerLecturerIdPatchData, UpdateLecturerLecturerIdPatchError, UpdateLecturerLecturerIdPatchResponse, UpdateLecturerRatingLecturerImportRatingPatchData, UpdateLecturerRatingLecturerImportRatingPatchError, UpdateLecturerRatingLecturerImportRatingPatchResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getLecturersLecturerGetQueryKey = (options?: Options<GetLecturersLecturerGetData>) => createQueryKey('getLecturersLecturerGet', options);

/**
 * Get Lecturers
 *
 * `limit` - максимальное количество возвращаемых преподавателей
 *
 * `offset` - нижняя граница получения преподавателей, т.е. если по дефолту первым возвращается преподаватель с условным номером N, то при наличии ненулевого offset будет возвращаться преподаватель с номером N + offset
 *
 * `order_by` - возможные значения `"mark_weighted", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "last_name"`.
 * Если передано `'last_name'` - возвращается список преподавателей отсортированных по алфавиту по фамилиям
 * Если передано `'mark_...'` - возвращается список преподавателей отсортированных по конкретной оценке
 * Если передано просто так (или с '+' в начале параметра), то сортирует по возрастанию
 * С '-' в начале -- по убыванию.
 *
 * *Пример запросов с этим параметром*:
 * - `...?order_by=-mark_kindness`
 * - `...?order_by=mark_freebie`
 * - `...?order_by=+mark_freebie` (эквивалентно 2ому пункту)
 *
 * `info` - возможные значения `'comments'`.
 * Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
 *
 * `subject`
 * Если передано `subject` - возвращает всех преподавателей, для которых переданное значение совпадает с одним из их предметов преподавания.
 * Также возвращает всех преподавателей, у которых есть комментарий с совпадающим с данным subject.
 *
 * `name`
 * Поле для ФИО. Если передано `name` - возвращает всех преподователей, для которых нашлись совпадения с переданной строкой
 *
 * `mark`
 * Поле для оценки. Если передано, то возвращает только тех преподавателей, для которых средняя общая оценка ('general_mark')
 * больше, чем переданный 'mark'.
 *
 * Исключение **ObjectNotFound**, если преподаватель с введенными параметрами не найден
 */
export const getLecturersLecturerGetOptions = (options?: Options<GetLecturersLecturerGetData>) => queryOptions<GetLecturersLecturerGetResponse, GetLecturersLecturerGetError, GetLecturersLecturerGetResponse, ReturnType<typeof getLecturersLecturerGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLecturersLecturerGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLecturersLecturerGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getLecturersLecturerGetInfiniteQueryKey = (options?: Options<GetLecturersLecturerGetData>): QueryKey<Options<GetLecturersLecturerGetData>> => createQueryKey('getLecturersLecturerGet', options, true);

/**
 * Get Lecturers
 *
 * `limit` - максимальное количество возвращаемых преподавателей
 *
 * `offset` - нижняя граница получения преподавателей, т.е. если по дефолту первым возвращается преподаватель с условным номером N, то при наличии ненулевого offset будет возвращаться преподаватель с номером N + offset
 *
 * `order_by` - возможные значения `"mark_weighted", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "last_name"`.
 * Если передано `'last_name'` - возвращается список преподавателей отсортированных по алфавиту по фамилиям
 * Если передано `'mark_...'` - возвращается список преподавателей отсортированных по конкретной оценке
 * Если передано просто так (или с '+' в начале параметра), то сортирует по возрастанию
 * С '-' в начале -- по убыванию.
 *
 * *Пример запросов с этим параметром*:
 * - `...?order_by=-mark_kindness`
 * - `...?order_by=mark_freebie`
 * - `...?order_by=+mark_freebie` (эквивалентно 2ому пункту)
 *
 * `info` - возможные значения `'comments'`.
 * Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
 *
 * `subject`
 * Если передано `subject` - возвращает всех преподавателей, для которых переданное значение совпадает с одним из их предметов преподавания.
 * Также возвращает всех преподавателей, у которых есть комментарий с совпадающим с данным subject.
 *
 * `name`
 * Поле для ФИО. Если передано `name` - возвращает всех преподователей, для которых нашлись совпадения с переданной строкой
 *
 * `mark`
 * Поле для оценки. Если передано, то возвращает только тех преподавателей, для которых средняя общая оценка ('general_mark')
 * больше, чем переданный 'mark'.
 *
 * Исключение **ObjectNotFound**, если преподаватель с введенными параметрами не найден
 */
export const getLecturersLecturerGetInfiniteOptions = (options?: Options<GetLecturersLecturerGetData>) => {
    const opts = infiniteQueryOptions<GetLecturersLecturerGetResponse, GetLecturersLecturerGetError, InfiniteData<GetLecturersLecturerGetResponse>, QueryKey<Options<GetLecturersLecturerGetData>>, number | Pick<QueryKey<Options<GetLecturersLecturerGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetLecturersLecturerGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getLecturersLecturerGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getLecturersLecturerGetInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create Lecturer
 *
 * Scopes: `["rating.lecturer.create"]`
 *
 * Создает преподавателя в базе данных
 *
 * Исключение **AlreadyExists**, если преподаватель с введеным `timetable_id` уже существует
 */
export const createLecturerLecturerPostMutation = (options?: Partial<Options<CreateLecturerLecturerPostData>>): UseMutationOptions<CreateLecturerLecturerPostResponse, CreateLecturerLecturerPostError, Options<CreateLecturerLecturerPostData>> => {
    const mutationOptions: UseMutationOptions<CreateLecturerLecturerPostResponse, CreateLecturerLecturerPostError, Options<CreateLecturerLecturerPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createLecturerLecturerPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Lecturer Rating
 *
 * Scopes: `["rating.lecturer.update_rating"]`
 *
 * Обновляет рейтинг преподавателя в базе данных
 */
export const updateLecturerRatingLecturerImportRatingPatchMutation = (options?: Partial<Options<UpdateLecturerRatingLecturerImportRatingPatchData>>): UseMutationOptions<UpdateLecturerRatingLecturerImportRatingPatchResponse, UpdateLecturerRatingLecturerImportRatingPatchError, Options<UpdateLecturerRatingLecturerImportRatingPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateLecturerRatingLecturerImportRatingPatchResponse, UpdateLecturerRatingLecturerImportRatingPatchError, Options<UpdateLecturerRatingLecturerImportRatingPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateLecturerRatingLecturerImportRatingPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLecturerByTimetableIdLecturerTimetableIdTimetableIdGetQueryKey = (options: Options<GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetData>) => createQueryKey('getLecturerByTimetableIdLecturerTimetableIdTimetableIdGet', options);

/**
 * Get Lecturer By Timetable Id
 *
 * Возвращает преподавателя по его timetable_id
 *
 * Исключение **ObjectNotFound**, если `timetable_id` не найден
 */
export const getLecturerByTimetableIdLecturerTimetableIdTimetableIdGetOptions = (options: Options<GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetData>) => queryOptions<GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetResponse, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetError, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetResponse, ReturnType<typeof getLecturerByTimetableIdLecturerTimetableIdTimetableIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLecturerByTimetableIdLecturerTimetableIdTimetableIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLecturerByTimetableIdLecturerTimetableIdTimetableIdGetQueryKey(options)
});

/**
 * Delete Lecturer
 *
 * Scopes: `["rating.lecturer.delete"]`
 *
 * Удаляет из базы данных преподавателя по его id
 *
 * Исключение **ObjectNotFound**, если `id` не найден
 */
export const deleteLecturerLecturerIdDeleteMutation = (options?: Partial<Options<DeleteLecturerLecturerIdDeleteData>>): UseMutationOptions<DeleteLecturerLecturerIdDeleteResponse, DeleteLecturerLecturerIdDeleteError, Options<DeleteLecturerLecturerIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteLecturerLecturerIdDeleteResponse, DeleteLecturerLecturerIdDeleteError, Options<DeleteLecturerLecturerIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteLecturerLecturerIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLecturerLecturerIdGetQueryKey = (options: Options<GetLecturerLecturerIdGetData>) => createQueryKey('getLecturerLecturerIdGet', options);

/**
 * Get Lecturer
 *
 * Scopes: `["rating.lecturer.read"]`
 *
 * Возвращает преподавателя по его ID в базе данных
 *
 * *QUERY* `info: string` - возможные значения `'comments'`.
 * Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
 * Subject лектора возвращается либо из базы данных, либо из любого аппрувнутого комментария
 *
 * Исключение **ObjectNotFound**, если `id` не найден
 */
export const getLecturerLecturerIdGetOptions = (options: Options<GetLecturerLecturerIdGetData>) => queryOptions<GetLecturerLecturerIdGetResponse, GetLecturerLecturerIdGetError, GetLecturerLecturerIdGetResponse, ReturnType<typeof getLecturerLecturerIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLecturerLecturerIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLecturerLecturerIdGetQueryKey(options)
});

/**
 * Update Lecturer
 *
 * Scopes: `["rating.lecturer.update"]`
 *
 * Обновляет данные о преподавателе по его id
 *
 * Исключение **ObjectNotFound**, если `id` не найден
 */
export const updateLecturerLecturerIdPatchMutation = (options?: Partial<Options<UpdateLecturerLecturerIdPatchData>>): UseMutationOptions<UpdateLecturerLecturerIdPatchResponse, UpdateLecturerLecturerIdPatchError, Options<UpdateLecturerLecturerIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateLecturerLecturerIdPatchResponse, UpdateLecturerLecturerIdPatchError, Options<UpdateLecturerLecturerIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateLecturerLecturerIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCommentsCommentGetQueryKey = (options?: Options<GetCommentsCommentGetData>) => createQueryKey('getCommentsCommentGet', options);

/**
 * Get Comments
 *
 * Scopes: `["rating.comment.review"]`
 *
 * `limit` - максимальное количество возвращаемых комментариев
 *
 * `offset` -  смещение, определяющее, с какого по порядку комментария начинать выборку.
 * Если без смещения возвращается комментарий с условным номером N,
 * то при значении offset = X будет возвращаться комментарий с номером N + X
 *
 * `order_by` - возможные значения `"create_ts", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "like_diff"`.
 * Если передано `'create_ts'` - возвращается список комментариев, отсортированных по времени
 * Если передано `'mark_...'` - возвращается список комментариев, отсортированных по конкретной оценке
 * Если передано `'like_diff'` - возвращается список комментариев, отсортированных по разнице лайков и дизлайков
 *
 * `lecturer_id` - вернет все комментарии для преподавателя с конкретным id, по дефолту возвращает вообще все аппрувнутые комментарии.
 *
 * `user_id` - вернет все комментарии пользователя с конкретным id
 *
 * `unreviewed` - вернет все непроверенные комментарии, если True. По дефолту False.
 *
 * `asc_order` -Если передано true, сортировать в порядке возрастания. Иначе - в порядке убывания
 *
 * Разные модели ответа в зависимости от прав пользователя:
 * CommentGetAllWithAllInfo: для модераторов (со статусом комментария);
 * CommentGetAllWithStatus: для авторов комментариев (со статусом);
 * CommentGetAll: для всех остальных (только одобренные комментарии)
 *
 * Исключение **ObjectNotFound**, если комментарий с введенными параметрами не найден
 *
 * Исключение **ForbiddenAction**, если пользователь пытается получить непроверенный комментарий
 */
export const getCommentsCommentGetOptions = (options?: Options<GetCommentsCommentGetData>) => queryOptions<GetCommentsCommentGetResponse, GetCommentsCommentGetError, GetCommentsCommentGetResponse, ReturnType<typeof getCommentsCommentGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCommentsCommentGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCommentsCommentGetQueryKey(options)
});

export const getCommentsCommentGetInfiniteQueryKey = (options?: Options<GetCommentsCommentGetData>): QueryKey<Options<GetCommentsCommentGetData>> => createQueryKey('getCommentsCommentGet', options, true);

/**
 * Get Comments
 *
 * Scopes: `["rating.comment.review"]`
 *
 * `limit` - максимальное количество возвращаемых комментариев
 *
 * `offset` -  смещение, определяющее, с какого по порядку комментария начинать выборку.
 * Если без смещения возвращается комментарий с условным номером N,
 * то при значении offset = X будет возвращаться комментарий с номером N + X
 *
 * `order_by` - возможные значения `"create_ts", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "like_diff"`.
 * Если передано `'create_ts'` - возвращается список комментариев, отсортированных по времени
 * Если передано `'mark_...'` - возвращается список комментариев, отсортированных по конкретной оценке
 * Если передано `'like_diff'` - возвращается список комментариев, отсортированных по разнице лайков и дизлайков
 *
 * `lecturer_id` - вернет все комментарии для преподавателя с конкретным id, по дефолту возвращает вообще все аппрувнутые комментарии.
 *
 * `user_id` - вернет все комментарии пользователя с конкретным id
 *
 * `unreviewed` - вернет все непроверенные комментарии, если True. По дефолту False.
 *
 * `asc_order` -Если передано true, сортировать в порядке возрастания. Иначе - в порядке убывания
 *
 * Разные модели ответа в зависимости от прав пользователя:
 * CommentGetAllWithAllInfo: для модераторов (со статусом комментария);
 * CommentGetAllWithStatus: для авторов комментариев (со статусом);
 * CommentGetAll: для всех остальных (только одобренные комментарии)
 *
 * Исключение **ObjectNotFound**, если комментарий с введенными параметрами не найден
 *
 * Исключение **ForbiddenAction**, если пользователь пытается получить непроверенный комментарий
 */
export const getCommentsCommentGetInfiniteOptions = (options?: Options<GetCommentsCommentGetData>) => {
    const opts = infiniteQueryOptions<GetCommentsCommentGetResponse, GetCommentsCommentGetError, InfiniteData<GetCommentsCommentGetResponse>, QueryKey<Options<GetCommentsCommentGetData>>, number | Pick<QueryKey<Options<GetCommentsCommentGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetCommentsCommentGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getCommentsCommentGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCommentsCommentGetInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create Comment
 *
 * Scopes: `["rating.comment.create"]`
 *
 * Создает комментарий к преподавателю в базе данных RatingAPI
 *
 * Комментарий создается со статусом PENDING (на модерации)
 *
 * Исключение **TooManyCommentRequests**, если число комментариев превысило общий лимит
 *
 * Исключение **TooManyCommentsToLecturer**, если число комментариев превысило лимит для лектора
 *
 * Исключение **CommentTooLong**, если комментарий слишком длинный
 *
 * Исключение **ForbiddenSymbol**, если в комментарии использованы запрещенные символы
 */
export const createCommentCommentPostMutation = (options?: Partial<Options<CreateCommentCommentPostData>>): UseMutationOptions<CreateCommentCommentPostResponse, CreateCommentCommentPostError, Options<CreateCommentCommentPostData>> => {
    const mutationOptions: UseMutationOptions<CreateCommentCommentPostResponse, CreateCommentCommentPostError, Options<CreateCommentCommentPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createCommentCommentPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Import Comments
 *
 * Scopes: `["rating.comment.import"]`
 *
 * Создает комментарии в базе данных
 */
export const importCommentsCommentImportPostMutation = (options?: Partial<Options<ImportCommentsCommentImportPostData>>): UseMutationOptions<ImportCommentsCommentImportPostResponse, ImportCommentsCommentImportPostError, Options<ImportCommentsCommentImportPostData>> => {
    const mutationOptions: UseMutationOptions<ImportCommentsCommentImportPostResponse, ImportCommentsCommentImportPostError, Options<ImportCommentsCommentImportPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await importCommentsCommentImportPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Comment
 *
 * Scopes: `["rating.comment.delete"]`
 *
 * Удаляет комментарий по его UUID в базе данных RatingAPI
 *
 * Модератор может удалить любой комментарий
 *
 * Обычный пользователь может удалить только свой неанонимный комментарий
 *
 * Анонимные комментарии может удалить только модератор
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 *
 * Исключение **ForbiddenAction** при попытке удалить комментарий пользователем без прав
 */
export const deleteCommentCommentUuidDeleteMutation = (options?: Partial<Options<DeleteCommentCommentUuidDeleteData>>): UseMutationOptions<DeleteCommentCommentUuidDeleteResponse, DeleteCommentCommentUuidDeleteError, Options<DeleteCommentCommentUuidDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteCommentCommentUuidDeleteResponse, DeleteCommentCommentUuidDeleteError, Options<DeleteCommentCommentUuidDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCommentCommentUuidDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCommentCommentUuidGetQueryKey = (options: Options<GetCommentCommentUuidGetData>) => createQueryKey('getCommentCommentUuidGet', options);

/**
 * Get Comment
 *
 * Scopes: `["rating.comment.read"]`
 *
 * Возвращает комментарий по его UUID в базе данных RatingAPI
 *
 * Если пользователь авторизован, добавляются флаги is_liked/is_disliked (реакция пользователя на комментарий)
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 */
export const getCommentCommentUuidGetOptions = (options: Options<GetCommentCommentUuidGetData>) => queryOptions<GetCommentCommentUuidGetResponse, GetCommentCommentUuidGetError, GetCommentCommentUuidGetResponse, ReturnType<typeof getCommentCommentUuidGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCommentCommentUuidGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCommentCommentUuidGetQueryKey(options)
});

/**
 * Update Comment
 *
 * Scopes: `["rating.comment.update"]`
 *
 * Позволяет изменить свой неанонимный комментарий
 *
 * После редактирования комментарий снова отправляется на модерацию
 *
 * Исключение **ForbiddenAction** при попытке отредактировать чужой комментарий
 *
 * Исключение **ForbiddenAction** при попытке отредактировать анонимный комментарий
 */
export const updateCommentCommentUuidPatchMutation = (options?: Partial<Options<UpdateCommentCommentUuidPatchData>>): UseMutationOptions<UpdateCommentCommentUuidPatchResponse, UpdateCommentCommentUuidPatchError, Options<UpdateCommentCommentUuidPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateCommentCommentUuidPatchResponse, UpdateCommentCommentUuidPatchError, Options<UpdateCommentCommentUuidPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateCommentCommentUuidPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Review Comment
 *
 * Scopes: `["rating.comment.review"]`
 * Проверка комментария и присваивания ему статуса по его UUID в базе данных RatingAPI
 *
 * `review_status` - возможные значения
 * `approved` - комментарий одобрен и возвращается при запросе лектора
 * `dismissed` - комментарий отклонен, не отображается в запросе лектора
 *
 * Комментарий может быть либо одобрен, либо отклонен
 *
 * Отклоненные комментарии не отображаются в обычных GET-запросах(можно посмотреть только через `uuid`)
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 */
export const reviewCommentCommentUuidReviewPatchMutation = (options?: Partial<Options<ReviewCommentCommentUuidReviewPatchData>>): UseMutationOptions<ReviewCommentCommentUuidReviewPatchResponse, ReviewCommentCommentUuidReviewPatchError, Options<ReviewCommentCommentUuidReviewPatchData>> => {
    const mutationOptions: UseMutationOptions<ReviewCommentCommentUuidReviewPatchResponse, ReviewCommentCommentUuidReviewPatchError, Options<ReviewCommentCommentUuidReviewPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reviewCommentCommentUuidReviewPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Like Comment
 *
 * Scopes: `["rating.comment.write"]`
 *
 * Ставит лайк или дизлайк на комментарий по его uuid
 *
 * Дизлайка и лайка не может быть одновременно
 *
 * Если реакции от пользователя на этот комментарий не было — создается новая;
 * Если была противоположная реакция — она заменяется на новую;
 * Если была такая же реакция — она удаляется;
 * После операции поля is_liked/is_disliked в ответе отражают итоговое состояние
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 */
export const likeCommentCommentUuidReactionPutMutation = (options?: Partial<Options<LikeCommentCommentUuidReactionPutData>>): UseMutationOptions<LikeCommentCommentUuidReactionPutResponse, LikeCommentCommentUuidReactionPutError, Options<LikeCommentCommentUuidReactionPutData>> => {
    const mutationOptions: UseMutationOptions<LikeCommentCommentUuidReactionPutResponse, LikeCommentCommentUuidReactionPutError, Options<LikeCommentCommentUuidReactionPutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await likeCommentCommentUuidReactionPut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
