// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCommentCommentPostData, CreateCommentCommentPostErrors, CreateCommentCommentPostResponses, CreateLecturerLecturerPostData, CreateLecturerLecturerPostErrors, CreateLecturerLecturerPostResponses, DeleteCommentCommentUuidDeleteData, DeleteCommentCommentUuidDeleteErrors, DeleteCommentCommentUuidDeleteResponses, DeleteLecturerLecturerIdDeleteData, DeleteLecturerLecturerIdDeleteErrors, DeleteLecturerLecturerIdDeleteResponses, GetCommentCommentUuidGetData, GetCommentCommentUuidGetErrors, GetCommentCommentUuidGetResponses, GetCommentsCommentGetData, GetCommentsCommentGetErrors, GetCommentsCommentGetResponses, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetData, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetErrors, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetResponses, GetLecturerLecturerIdGetData, GetLecturerLecturerIdGetErrors, GetLecturerLecturerIdGetResponses, GetLecturersLecturerGetData, GetLecturersLecturerGetErrors, GetLecturersLecturerGetResponses, ImportCommentsCommentImportPostData, ImportCommentsCommentImportPostErrors, ImportCommentsCommentImportPostResponses, LikeCommentCommentUuidReactionPutData, LikeCommentCommentUuidReactionPutErrors, LikeCommentCommentUuidReactionPutResponses, ReviewCommentCommentUuidReviewPatchData, ReviewCommentCommentUuidReviewPatchErrors, ReviewCommentCommentUuidReviewPatchResponses, UpdateCommentCommentUuidPatchData, UpdateCommentCommentUuidPatchErrors, UpdateCommentCommentUuidPatchResponses, UpdateLecturerLecturerIdPatchData, UpdateLecturerLecturerIdPatchErrors, UpdateLecturerLecturerIdPatchResponses, UpdateLecturerRatingLecturerImportRatingPatchData, UpdateLecturerRatingLecturerImportRatingPatchErrors, UpdateLecturerRatingLecturerImportRatingPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Lecturers
 *
 * `limit` - максимальное количество возвращаемых преподавателей
 *
 * `offset` - нижняя граница получения преподавателей, т.е. если по дефолту первым возвращается преподаватель с условным номером N, то при наличии ненулевого offset будет возвращаться преподаватель с номером N + offset
 *
 * `order_by` - возможные значения `"mark_weighted", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "last_name"`.
 * Если передано `'last_name'` - возвращается список преподавателей отсортированных по алфавиту по фамилиям
 * Если передано `'mark_...'` - возвращается список преподавателей отсортированных по конкретной оценке
 * Если передано просто так (или с '+' в начале параметра), то сортирует по возрастанию
 * С '-' в начале -- по убыванию.
 *
 * *Пример запросов с этим параметром*:
 * - `...?order_by=-mark_kindness`
 * - `...?order_by=mark_freebie`
 * - `...?order_by=+mark_freebie` (эквивалентно 2ому пункту)
 *
 * `info` - возможные значения `'comments'`.
 * Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
 *
 * `subject`
 * Если передано `subject` - возвращает всех преподавателей, для которых переданное значение совпадает с одним из их предметов преподавания.
 * Также возвращает всех преподавателей, у которых есть комментарий с совпадающим с данным subject.
 *
 * `name`
 * Поле для ФИО. Если передано `name` - возвращает всех преподователей, для которых нашлись совпадения с переданной строкой
 *
 * `mark`
 * Поле для оценки. Если передано, то возвращает только тех преподавателей, для которых средняя общая оценка ('general_mark')
 * больше, чем переданный 'mark'.
 *
 * Исключение **ObjectNotFound**, если преподаватель с введенными параметрами не найден
 */
export const getLecturersLecturerGet = <ThrowOnError extends boolean = false>(options?: Options<GetLecturersLecturerGetData, ThrowOnError>): RequestResult<GetLecturersLecturerGetResponses, GetLecturersLecturerGetErrors, ThrowOnError> => (options?.client ?? client).get<GetLecturersLecturerGetResponses, GetLecturersLecturerGetErrors, ThrowOnError>({ url: '/lecturer', ...options });

/**
 * Create Lecturer
 *
 * Scopes: `["rating.lecturer.create"]`
 *
 * Создает преподавателя в базе данных
 *
 * Исключение **AlreadyExists**, если преподаватель с введеным `timetable_id` уже существует
 */
export const createLecturerLecturerPost = <ThrowOnError extends boolean = false>(options: Options<CreateLecturerLecturerPostData, ThrowOnError>): RequestResult<CreateLecturerLecturerPostResponses, CreateLecturerLecturerPostErrors, ThrowOnError> => (options.client ?? client).post<CreateLecturerLecturerPostResponses, CreateLecturerLecturerPostErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/lecturer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Lecturer Rating
 *
 * Scopes: `["rating.lecturer.update_rating"]`
 *
 * Обновляет рейтинг преподавателя в базе данных
 */
export const updateLecturerRatingLecturerImportRatingPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateLecturerRatingLecturerImportRatingPatchData, ThrowOnError>): RequestResult<UpdateLecturerRatingLecturerImportRatingPatchResponses, UpdateLecturerRatingLecturerImportRatingPatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateLecturerRatingLecturerImportRatingPatchResponses, UpdateLecturerRatingLecturerImportRatingPatchErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/lecturer/import_rating',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Lecturer By Timetable Id
 *
 * Возвращает преподавателя по его timetable_id
 *
 * Исключение **ObjectNotFound**, если `timetable_id` не найден
 */
export const getLecturerByTimetableIdLecturerTimetableIdTimetableIdGet = <ThrowOnError extends boolean = false>(options: Options<GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetData, ThrowOnError>): RequestResult<GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetResponses, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetResponses, GetLecturerByTimetableIdLecturerTimetableIdTimetableIdGetErrors, ThrowOnError>({ url: '/lecturer/timetable-id/{timetable_id}', ...options });

/**
 * Delete Lecturer
 *
 * Scopes: `["rating.lecturer.delete"]`
 *
 * Удаляет из базы данных преподавателя по его id
 *
 * Исключение **ObjectNotFound**, если `id` не найден
 */
export const deleteLecturerLecturerIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteLecturerLecturerIdDeleteData, ThrowOnError>): RequestResult<DeleteLecturerLecturerIdDeleteResponses, DeleteLecturerLecturerIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteLecturerLecturerIdDeleteResponses, DeleteLecturerLecturerIdDeleteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/lecturer/{id}',
    ...options
});

/**
 * Get Lecturer
 *
 * Scopes: `["rating.lecturer.read"]`
 *
 * Возвращает преподавателя по его ID в базе данных
 *
 * *QUERY* `info: string` - возможные значения `'comments'`.
 * Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
 * Subject лектора возвращается либо из базы данных, либо из любого аппрувнутого комментария
 *
 * Исключение **ObjectNotFound**, если `id` не найден
 */
export const getLecturerLecturerIdGet = <ThrowOnError extends boolean = false>(options: Options<GetLecturerLecturerIdGetData, ThrowOnError>): RequestResult<GetLecturerLecturerIdGetResponses, GetLecturerLecturerIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetLecturerLecturerIdGetResponses, GetLecturerLecturerIdGetErrors, ThrowOnError>({ url: '/lecturer/{id}', ...options });

/**
 * Update Lecturer
 *
 * Scopes: `["rating.lecturer.update"]`
 *
 * Обновляет данные о преподавателе по его id
 *
 * Исключение **ObjectNotFound**, если `id` не найден
 */
export const updateLecturerLecturerIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateLecturerLecturerIdPatchData, ThrowOnError>): RequestResult<UpdateLecturerLecturerIdPatchResponses, UpdateLecturerLecturerIdPatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateLecturerLecturerIdPatchResponses, UpdateLecturerLecturerIdPatchErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/lecturer/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Comments
 *
 * Scopes: `["rating.comment.review"]`
 *
 * `limit` - максимальное количество возвращаемых комментариев
 *
 * `offset` -  смещение, определяющее, с какого по порядку комментария начинать выборку.
 * Если без смещения возвращается комментарий с условным номером N,
 * то при значении offset = X будет возвращаться комментарий с номером N + X
 *
 * `order_by` - возможные значения `"create_ts", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "like_diff"`.
 * Если передано `'create_ts'` - возвращается список комментариев, отсортированных по времени
 * Если передано `'mark_...'` - возвращается список комментариев, отсортированных по конкретной оценке
 * Если передано `'like_diff'` - возвращается список комментариев, отсортированных по разнице лайков и дизлайков
 *
 * `lecturer_id` - вернет все комментарии для преподавателя с конкретным id, по дефолту возвращает вообще все аппрувнутые комментарии.
 *
 * `user_id` - вернет все комментарии пользователя с конкретным id
 *
 * `unreviewed` - вернет все непроверенные комментарии, если True. По дефолту False.
 *
 * `asc_order` -Если передано true, сортировать в порядке возрастания. Иначе - в порядке убывания
 *
 * Разные модели ответа в зависимости от прав пользователя:
 * CommentGetAllWithAllInfo: для модераторов (со статусом комментария);
 * CommentGetAllWithStatus: для авторов комментариев (со статусом);
 * CommentGetAll: для всех остальных (только одобренные комментарии)
 *
 * Исключение **ObjectNotFound**, если комментарий с введенными параметрами не найден
 *
 * Исключение **ForbiddenAction**, если пользователь пытается получить непроверенный комментарий
 */
export const getCommentsCommentGet = <ThrowOnError extends boolean = false>(options?: Options<GetCommentsCommentGetData, ThrowOnError>): RequestResult<GetCommentsCommentGetResponses, GetCommentsCommentGetErrors, ThrowOnError> => (options?.client ?? client).get<GetCommentsCommentGetResponses, GetCommentsCommentGetErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment',
    ...options
});

/**
 * Create Comment
 *
 * Scopes: `["rating.comment.create"]`
 *
 * Создает комментарий к преподавателю в базе данных RatingAPI
 *
 * Комментарий создается со статусом PENDING (на модерации)
 *
 * Исключение **TooManyCommentRequests**, если число комментариев превысило общий лимит
 *
 * Исключение **TooManyCommentsToLecturer**, если число комментариев превысило лимит для лектора
 *
 * Исключение **CommentTooLong**, если комментарий слишком длинный
 *
 * Исключение **ForbiddenSymbol**, если в комментарии использованы запрещенные символы
 */
export const createCommentCommentPost = <ThrowOnError extends boolean = false>(options: Options<CreateCommentCommentPostData, ThrowOnError>): RequestResult<CreateCommentCommentPostResponses, CreateCommentCommentPostErrors, ThrowOnError> => (options.client ?? client).post<CreateCommentCommentPostResponses, CreateCommentCommentPostErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Import Comments
 *
 * Scopes: `["rating.comment.import"]`
 *
 * Создает комментарии в базе данных
 */
export const importCommentsCommentImportPost = <ThrowOnError extends boolean = false>(options: Options<ImportCommentsCommentImportPostData, ThrowOnError>): RequestResult<ImportCommentsCommentImportPostResponses, ImportCommentsCommentImportPostErrors, ThrowOnError> => (options.client ?? client).post<ImportCommentsCommentImportPostResponses, ImportCommentsCommentImportPostErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment/import',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Comment
 *
 * Scopes: `["rating.comment.delete"]`
 *
 * Удаляет комментарий по его UUID в базе данных RatingAPI
 *
 * Модератор может удалить любой комментарий
 *
 * Обычный пользователь может удалить только свой неанонимный комментарий
 *
 * Анонимные комментарии может удалить только модератор
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 *
 * Исключение **ForbiddenAction** при попытке удалить комментарий пользователем без прав
 */
export const deleteCommentCommentUuidDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteCommentCommentUuidDeleteData, ThrowOnError>): RequestResult<DeleteCommentCommentUuidDeleteResponses, DeleteCommentCommentUuidDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteCommentCommentUuidDeleteResponses, DeleteCommentCommentUuidDeleteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment/{uuid}',
    ...options
});

/**
 * Get Comment
 *
 * Scopes: `["rating.comment.read"]`
 *
 * Возвращает комментарий по его UUID в базе данных RatingAPI
 *
 * Если пользователь авторизован, добавляются флаги is_liked/is_disliked (реакция пользователя на комментарий)
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 */
export const getCommentCommentUuidGet = <ThrowOnError extends boolean = false>(options: Options<GetCommentCommentUuidGetData, ThrowOnError>): RequestResult<GetCommentCommentUuidGetResponses, GetCommentCommentUuidGetErrors, ThrowOnError> => (options.client ?? client).get<GetCommentCommentUuidGetResponses, GetCommentCommentUuidGetErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment/{uuid}',
    ...options
});

/**
 * Update Comment
 *
 * Scopes: `["rating.comment.update"]`
 *
 * Позволяет изменить свой неанонимный комментарий
 *
 * После редактирования комментарий снова отправляется на модерацию
 *
 * Исключение **ForbiddenAction** при попытке отредактировать чужой комментарий
 *
 * Исключение **ForbiddenAction** при попытке отредактировать анонимный комментарий
 */
export const updateCommentCommentUuidPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateCommentCommentUuidPatchData, ThrowOnError>): RequestResult<UpdateCommentCommentUuidPatchResponses, UpdateCommentCommentUuidPatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateCommentCommentUuidPatchResponses, UpdateCommentCommentUuidPatchErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment/{uuid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Review Comment
 *
 * Scopes: `["rating.comment.review"]`
 * Проверка комментария и присваивания ему статуса по его UUID в базе данных RatingAPI
 *
 * `review_status` - возможные значения
 * `approved` - комментарий одобрен и возвращается при запросе лектора
 * `dismissed` - комментарий отклонен, не отображается в запросе лектора
 *
 * Комментарий может быть либо одобрен, либо отклонен
 *
 * Отклоненные комментарии не отображаются в обычных GET-запросах(можно посмотреть только через `uuid`)
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 */
export const reviewCommentCommentUuidReviewPatch = <ThrowOnError extends boolean = false>(options: Options<ReviewCommentCommentUuidReviewPatchData, ThrowOnError>): RequestResult<ReviewCommentCommentUuidReviewPatchResponses, ReviewCommentCommentUuidReviewPatchErrors, ThrowOnError> => (options.client ?? client).patch<ReviewCommentCommentUuidReviewPatchResponses, ReviewCommentCommentUuidReviewPatchErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment/{uuid}/review',
    ...options
});

/**
 * Like Comment
 *
 * Scopes: `["rating.comment.write"]`
 *
 * Ставит лайк или дизлайк на комментарий по его uuid
 *
 * Дизлайка и лайка не может быть одновременно
 *
 * Если реакции от пользователя на этот комментарий не было — создается новая;
 * Если была противоположная реакция — она заменяется на новую;
 * Если была такая же реакция — она удаляется;
 * После операции поля is_liked/is_disliked в ответе отражают итоговое состояние
 *
 * Исключение **ObjectNotFound**, если `uuid` не найден
 */
export const likeCommentCommentUuidReactionPut = <ThrowOnError extends boolean = false>(options: Options<LikeCommentCommentUuidReactionPutData, ThrowOnError>): RequestResult<LikeCommentCommentUuidReactionPutResponses, LikeCommentCommentUuidReactionPutErrors, ThrowOnError> => (options.client ?? client).put<LikeCommentCommentUuidReactionPutResponses, LikeCommentCommentUuidReactionPutErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/comment/{uuid}/{reaction}',
    ...options
});
